### ISSUE TITLE
plugin integration

### ISSUE THREAD

**Issue by pnn** [wehjs/weh#1]
brainstorm issue for better plugin integration:

- currently, `site.hook` isn't enough
  - if a plugin exposes multiple hooks, it'd be hard to integrate all of them
- therefore, a proposal: `site.plugin(obj)`
  - takes an object that exposes multiple hooks

```
{
  pre_write: function (site) { ... },
  pre_read: function (site) { ... },
  etc...
}
```

- allows for plugin installation in one line (at least user-facing)

ALSO: priority support
- some plugins will depend on others
- for example: a drafts plugin would depend on a front-matter plugin
- solution: provide a priority ordering system in which hooks are executed
- for example: one sets `site.collections`, the more low-priority ones use it
- maybe integrate with `site.plugin(obj)`?

```
{
  pre_read: {
    priority: 1,
    fn: function (site) { ... }
  },
  etc...
}
```

**Comment by cilice** [comment]
In my opinion, priorities are really hard to debug at some point. Just make the plugins not discoverable automatically but rather enforce the order in the confugration, and apply plugins according to the array order.

**Comment by pnn** [comment]
@cilice i agree, but that still leaves the user to apply the plugins in the right order, which could become an inconvenience
